CREATE SCHEMA PUBLIC AUTHORIZATION DBA
CREATE TABLE Edible(EdibleID INTEGER IDENTITY PRIMARY KEY,Name VARCHAR(9999) not null,Description VARCHAR(9999),Quantity INTEGER not null,Unit VARCHAR(9999) not null,Calories INTEGER not null,Protein INTEGER not null,Carbs INTEGER not null,Fat INTEGER not null,Photo BINARY,IsAlcoholic BOOLEAN not null,IsSpicy BOOLEAN not null,IsVegan BOOLEAN not null,IsVegetarian BOOLEAN not null,IsGlutenFree BOOLEAN not null)
CREATE TABLE Food(EdibleID INTEGER not null,FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID))
CREATE TABLE Meal(EdibleID INTEGER not null,Instructions VARCHAR(9999),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID))
CREATE TABLE Drink(EdibleID INTEGER not null,Instructions VARCHAR(9999),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID))
CREATE TABLE CustomEdible(CustomEdibleID INTEGER IDENTITY PRIMARY KEY,UserID INTEGER not null,Name VARCHAR(9999) not null,Description VARCHAR(9999),Quantity INTEGER not null,Unit VARCHAR(9999) not null,Calories INTEGER not null,Protein INTEGER not null,Carbs INTEGER not null,Fat INTEGER not null,Photo BINARY,IsAlcoholic BOOLEAN not null,IsSpicy BOOLEAN not null,IsVegan BOOLEAN not null,IsVegetarian BOOLEAN not null,IsGlutenFree BOOLEAN not null)
CREATE TABLE CustomFood(CustomEdibleID INTEGER not null,FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE TABLE CustomMeal(CustomEdibleID INTEGER not null,Instructions VARCHAR(9999),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE TABLE CustomDrink(CustomEdibleID INTEGER not null,Instructions VARCHAR(9999),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE TABLE MealIngredient(PreparedID INTEGER,PreparedCustomID INTEGER,EdibleID INTEGER,CustomEdibleID INTEGER,Quantity INTEGER not null,Unit VARCHAR(9999) not null,FOREIGN KEY(PreparedID) REFERENCES Edible(EdibleID),FOREIGN KEY(PreparedCustomID) REFERENCES CustomEdible(CustomEdibleID),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE TABLE DrinkIngredient(PreparedID INTEGER,PreparedCustomID INTEGER,EdibleID INTEGER,CustomEdibleID INTEGER,Quantity INTEGER not null,Unit VARCHAR(9999) not null,Substitute BOOLEAN not null,FOREIGN KEY(PreparedID) REFERENCES Edible(EdibleID),FOREIGN KEY(PreparedCustomID) REFERENCES CustomEdible(CustomEdibleID),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE TABLE USER(UserID INTEGER IDENTITY PRIMARY KEY,Name VARCHAR(9999),Height INTEGER,Weight INTEGER,CalorieGoal INTEGER not null,ExerciseGoal INTEGER)
CREATE TABLE History(HistoryID INTEGER IDENTITY PRIMARY KEY,UserID INTEGER not null,Date DATE not null,CalorieGoal INTEGER not null,CalorieActual INTEGER not null,FOREIGN KEY(UserID) REFERENCES User(UserID))
CREATE TABLE EdibleHistory(HistoryID INTEGER not null,EdibleID INTEGER,CustomEdibleID INTEGER,Quantity INTEGER not null,Unit VARCHAR(9999) not null,FOREIGN KEY(HistoryID) REFERENCES History(HistoryID) ON DELETE CASCADE,FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE TABLE WorkoutHistory(HistoryID INTEGER not null,ExerciseActual INTEGER not null,FOREIGN KEY(HistoryID) REFERENCES History(HistoryID))
CREATE USER SA PASSWORD ""
GRANT DBA TO SA
SET WRITE_DELAY 20
SET SCHEMA PUBLIC