CREATE SCHEMA EATEN AUTHORIZATION DBA
CREATE MEMORY TABLE Edible(EdibleID INTEGER PRIMARY KEY AUTOINCREMENT,Name VARCHAR(9999) not null,Description VARCHAR(9999),Quantity INTEGER not null,Unit VARCHAR(9999) not null,Calories INTEGER not null,Protein INTEGER not null,Carbs INTEGER not null,Fat INTEGER not null,Photo BLOB,IsAlcoholic BOOLEAN not null,IsSpicy BOOLEAN not null,IsVegan BOOLEAN not null,IsVegetarian BOOLEAN not null,IsGlutenFree BOOLEAN not null)
CREATE MEMORY TABLE Food(EdibleID INTEGER not null,FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID))
CREATE MEMORY TABLE Meal(EdibleID INTEGER not null,Instructions VARCHAR(9999),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID))
CREATE MEMORY TABLE Drink(EdibleID INTEGER not null,Instructions VARCHAR(9999),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID))
CREATE MEMORY TABLE CustomEdible(CustomEdibleID INTEGER PRIMARY KEY AUTOINCREMENT,UserID INTEGER not null,Name VARCHAR(9999) not null,Description VARCHAR(9999),Quantity INTEGER not null,Unit VARCHAR(9999) not null,Calories INTEGER not null,Protein INTEGER not null,Carbs INTEGER not null,Fat INTEGER not null,Photo BLOB,IsAlcoholic BOOLEAN not null,IsSpicy BOOLEAN not null,IsVegan BOOLEAN not null,IsVegetarian BOOLEAN not null,IsGlutenFree BOOLEAN not nul)
CREATE MEMORY TABLE CustomFood(CustomEdibleID INTEGER not null,FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE MEMORY TABLE CustomMeal(CustomEdibleID INTEGER not null,Instructions VARCHAR(9999)FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE MEMORY TABLE CustomDrink(CustomEdibleID INTEGER not null,Instructions VARCHAR(9999),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE MEMORY TABLE MealIngredient(PreparedID INTEGER,PreparedCustomID INTEGER,EdibleID INTEGER,CustomEdibleID INTEGER,Quantity INTEGER not null,Unit VARCHAR(9999) not null,FOREIGN KEY(PreparedID) REFERENCES Edible(EdibleID),FOREIGN KEY(PreparedCustomID) REFERENCES CustomEdible(CustomEdibleID),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE MEMORY TABLE DrinkIngredient(PreparedID INTEGER,PreparedCustomID INTEGER,EdibleID INTEGER,CustomEdibleID INTEGER,Quantity INTEGER not null,Unit VARCHAR(9999) not null,Substitute BOOLEAN not null,FOREIGN KEY(PreparedID) REFERENCES Edible(EdibleID),FOREIGN KEY(PreparedCustomID) REFERENCES CustomEdible(CustomEdibleID),FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE MEMORY TABLE User(UserID INTEGER PRIMARY KEY AUTOINCREMENT,Name VARCHAR(9999),Height INTEGER,Weight INTEGER,CalorieGoal INTEGER not null,ExerciseGoal INTEGER)
CREATE MEMORY TABLE History(HistoryID INTEGER PRIMARY KEY AUTOINCREMENT,UserID INTEGER not null,Date DATE not null,CalorieGoal INTEGER not null,CalorieActual INTEGER not null,FOREIGN KEY(UserID) REFERENCES User(UserID))
CREATE MEMORY TABLE EdibleHistory(HistoryID INTEGER not null,EdibleID INTEGER,CustomEdibleID INTEGER,Quantity INTEGER not null,Unit VARCHAR(9999) not null,FOREIGN KEY(HistoryID) REFERENCES History(HistoryID) ON DELETE CASCADE,FOREIGN KEY(EdibleID) REFERENCES Edible(EdibleID),FOREIGN KEY(CustomEdibleID) REFERENCES CustomEdible(CustomEdibleID))
CREATE MEMORY TABLE WorkoutHistory(HistoryID INTEGER not null,ExerciseActual INTEGER not null,FOREIGN KEY(HistoryID) REFERENCES History(HistoryID))
CREATE USER SA PASSWORD ""
GRANT DBA SA
SET WRITE_DELAY 20
SET SCHEMA EATEN
INSERT INTO User ('Name','Height','Weight','CalorieGoal','ExerciseGoal') VALUES('GIVE ME A+',100,100,1000,50)